### ISSUE TITLE
Performance: get_matching_ad_code is SLOOOOOW

### ISSUE THREAD

**Issue by rinatkhaziev** [Automattic/Ad-Code-Manager#78]
Last night I did some profiling and found that this method might get extremely slow when there's significant amount of ad codes in db to iterate over and match against. 

60 ad codes \* 5 tags on the page add 300ms to request time easily. 

So I  added some caching that caches each ad tag on per request basis, but there might be a better/smarter solution.

**Comment by GaryJones** [comment]
Handled in #77.
