### ISSUE TITLE
action_acm_tag() has a flag to return instead of echo but you can't return out of do_action()

### ISSUE THREAD

**Issue by tmtrademark** [Automattic/ad-code-manager#94]
do_action() will never return a value, so having the flag is meaningless.

**Comment by GaryJones** [comment]
In the [Ad_Code_Manager::shortcode()](https://github.com/Automattic/Ad-Code-Manager/blob/4976f7bbb2ea8188b083acbd0becc10bc2bbe95a/ad-code-manager.php#L1096), there's a `return $this->action_acm_tag( $id, false );`, so it's this secondary use of the `action_acm_tag()` that the `$echo` parameter is being used for.

That said, I do think this could be refactored into a function that always returns the tag value (which can be called for the shortcode output), and a separate function which echo's the return from that first function (for the `add_action()` call).
